### ISSUE TITLE
check some calculations for reformatted output

### ISSUE THREAD

**Issue by fawda123** [SCCWRP/ASCI#12]
Line number links are below, provided by description of what it's supposed to do:

* Diatom, soft-bodied and algae data subsets, are we subsetting these correctly (i.e., diatoms are integrated, etc.)
     * diatoms https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/mmifun.R#L50
     * soft-bodied https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/mmifun.R#L57
     * hybrid https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/mmifun.R#L68
* Percent attributed taxa relevant for each metric
     * diatoms https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/mmifun.R#L118
     * soft-bodied https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/mmifun.R#L135
     * hybrid https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/mmifun.R#L149
* Check biovolume and sample counts 
     * diatoms https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/ASCI.R#L75
     * soft-bodied https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/ASCI.R#L83
* Check percent unrecognized taxa calculations https://github.com/SCCWRP/ASCI/blob/6ccc821db002cb10bec7a1269ffd8c9652898210/R/ASCI.R#L85

**Comment by stheroux** [comment]
Separating diatoms/sba by integrated/not integrated is good, and then there also needs to be a check for diatoms = BAResult and sba=Result (I think you already have this).

**Comment by stheroux** [comment]
I think calculating the % attributed taxa for each metric is likely redundant (bc many metrics are a "proportion of taxa" metric, you will get the same number). I think what is more useful is % of TOTAL diatom, sba, and hybrid metrics that have attributes for the metrics in the MMIs. Does that make sense? So you would just add the percentages you have already calculated.

**Comment by stheroux** [comment]
The S_EntityCount should be the sum of sba Result data in the macroalgae fraction. The S_Biovolume should be the sum of sba Result in the microalgae fraction.

**Comment by stheroux** [comment]
UnrecognizedTaxa looks good.

**Comment by fawda123** [comment]
@stheroux can you please elaborate on the % attributed taxa calcs?

**Comment by stheroux** [comment]
% attributed taxa should be the % of taxa in the sample that have a trait attribute for any of the 4 (or 5 or whatever it is) metrics in each MMI. So if a sample has 10 diatom taxa, and 2 of those taxa have ZERO trait attribute values for the 4 metrics in the diatom MMI, the % trait attributed taxa = 80%. Does that make sense?

**Comment by qthi24** [comment]
When we talk about **trait attribute values**, is that value calculated in every metrics? If so, what do we call that value? Is there a way to keep track of how many out of the total taxa did not contribute to the metric (base on what values/ criteria)?
