### ISSUE TITLE
Negative diatom valve counts 

### ISSUE THREAD

**Issue by stheroux** [SCCWRP/ASCI#25]
When a sample has no "integrated" fraction, diatom valve count _should_ equal 0. Instead, the ASCI calculator is returning negative values. This section of code likely needs to be modified (sorry I can't edit pipes!). Probably lines 68-74 in ASCI.R.

**Comment by r7butler** [comment]
If you click the link for that above commit, you'll see the fix that was implemented.

Filtering out Integrated sampletypes completely was likely creating an empty dataframe, which I assume R didn't like. Basically instead of 
extra1 <- dat %>% 
    filter(SampleTypeCode == 'Integrated') %>% 
    group_by(SampleID) %>%
    summarize(
      D_ValveCount = sum(BAResult, na.rm = T)
    )

We did:
extra1 <- dat %>% 
    group_by(SampleID) %>%
    summarize(
       D_ValveCount = sum(BAResult[which(SampleTypeCode == 'Integrated')], na.rm = T)
    )
