### ISSUE TITLE
Demo data not running

### ISSUE THREAD

**Issue by stheroux** [SCCWRP/ASCI#28]
Getting the following error message when running the demo data: 
Error in prop.spp.BCG12/richness : 
  non-numeric argument to binary operator

Thanks!

**Comment by r7butler** [comment]
Hey Susie, are you sure you have the latest version installed?
> library(devtools)
> install_github("SCCWRP/ASCI")
CRTL+SHIFT+F10 (Restart the R session)
>ASCI(demo_algae_tax,demo_station)

I ran that, and i didn't get any errors
