### ISSUE TITLE
Changes to oescr and pmmiscr functions

### ISSUE THREAD

**Issue by raphaelmazor** [SCCWRP/ASCI#4]
Some of these are long term, and others are quickies:
1. Drop null outputs
2. Drop BC outputs (or make that a toggle option, default to suppressed)
3. Add  percentiles: round(pnorm(OoverE, mean, sd), digits=2)
4. Let's go for some consistency with the CSCI reporting names (e.g., call this a "core" report, rather than "Scores"
4. We need a few more reports added:
4.a: A site by group probability matrix (like CSCI's Suppl1_grps report)
4.b: A sample-otu-count-captureprob flat file (like CSCI's Suppl1_oe report) (use the same field names to the extent possible)
5. Add StationCode and SampleID as variables to each relevant report
6. For the pMMI outputs, we need each metric to have raw, predicted, and scored values (lke CSCI's Suppl1_mmi report)
7. Combine get the OE and MMI results integrated into a single report. Have user provide options on which indices to return
8. Because there's a subsampling step, we should return the subsampled results
8a. Because there's a subsampling step, we may want to follow the CSCI's example and do this iteratively (and return the appropriate results). This is a Susie decision, I think, but it would be good for her to know if that's a huge pain in the butt.
8b: Because there's a subsampling option, we should give the user the ability to set a seed. (Or we can prompt them in documentation)
9.  We'll need to think about appropriate QA, like we have for the CSCI. Again, a Susie decision. But here are a few things I think are certain:
-Diatom count
-SBA count
-% ambiguous individuals (for O/E)
-% ambiguous taxa (for O/E)
10. In general, we should think about the kinds of error-checking we need, with the intention of creating informative error messages. Some examples:
-Checking that you have all the required fields in the inputs
-Checking that all sites in the taxonomy data show up in the stations data.
-Making the taxonomic data case-insensitive

Ok, that's all for now.

**Comment by fawda123** [comment]
1 - 628213b8e462e7d32739b48ff5a334640277cad8

**Comment by fawda123** [comment]
2 - 33cc447749124d54c87a1d112c2d5e1c62f76c87

**Comment by fawda123** [comment]
3 - 09b98cc6f9510d1e45e800cd10a8564354e7e27e

**Comment by fawda123** [comment]
7 (partially) - 7ecc162db3495ae3920163e36cd2183ad98aa6b5

**Comment by fawda123** [comment]
4, 5, 8 - 46047c29ee1bc22f7e40593d114bb12c747a2d5c

**Comment by fawda123** [comment]
11 - eda24a74fc0380192a99c889f61750412ef5e953, see the file `R/chkinp.R`.  In this commit it checks for required columns, sites in bug data match sites in env data, and correct taxonomy.
