### ISSUE TITLE
Taxa counts are counting taxa twice if in two different SampleTypeCodes

### ISSUE THREAD

**Issue by stheroux** [SCCWRP/ASCI#44]
We need to make Taxa Counts (S_NumberTaxa,D_NumberTaxa, etc) occur on a dataframe that does not include SampleTypeCode. e.g: 

Right now: 
Epiphyte Species A 
Microalgae Species A 
Microalgae Species B
S_NumberTaxa == 3 

It should be: 
Epiphyte Species A 
Microalgae Species A 
Microalgae Species B
S_NumberTaxa == 2

**Comment by r7butler** [comment]
@stheroux  I pushed up a commit which i think fixes it

On the dev branch, now it gets D_NumberTaxa by doing this
D_NumberTaxa = length(unique(FinalID[which((SampleTypeCode == 'Integrated') & (Phylum == 'Bacillariophyta'))]))

Count the number of unique FinalID's where the SampleTypeCode is Integrated and the Phylum is Bacillariophyta

H_NumberTaxa simply gets the number of unique FinalID's

S_NumberTaxa is being calculated by doing H_NumberTaxa - D_NumberTaxa

Hopefully that is correct, let me know if that seems wrong

**Comment by stheroux** [comment]
Humph, I can't get my numbers to line up. Just testing this on the demo algae tax, and for sample 909M24937 I get a H_NumberTaxa of either 65 (if you use FinalIDassigned) or 68 (if you use FinalID). The results gives you a value of 73. Any chance you can figure out where the 73 is coming from?

**Comment by stheroux** [comment]
That worked!
