### ISSUE TITLE
Run ASCI with either diatoms or SBA alone

### ISSUE THREAD

**Issue by stheroux** [SCCWRP/ASCI#46]
Allow users to submit single assemblage and calculate scores. Include flag.

**Comment by stheroux** [comment]
If I remove all diatom taxa, I get this error: Error in predict.randomForest(rfmods$diatoms.cnt.spp.most.tol, c(XerMtn,  : 
  number of variables in newdata does not match that in the training data

**Comment by stheroux** [comment]
If I remove all SBA data, I get just a warning message that one assemblage is missing

**Comment by stheroux** [comment]
Circling back about this, please let me know if you have any questions! Thanks!

**Comment by stheroux** [comment]
When I run the demo data with only SBA taxa: 
Error in predict.randomForest(rfmods$diatoms.cnt.spp.most.tol, c(XerMtn,  : 
  number of variables in newdata does not match that in the training data
In addition: Warning messages:
1: In chkinp(taxa, stations) :
  Only diatom or soft-bodied algae present at sites: 404M07357_2016-06-13_1, 801M16916_2016-05-25_1, 909M24937_2016-06-22_1
2: Column `FinalID` joining character vector and factor, coercing into character vector 
3: Column `FinalIDassigned` joining factors with different levels, coercing to character vector 
4: Column `FinalIDassigned` joining character vector and factor, coercing into character vector

**Comment by stheroux** [comment]
When I run the demo data with only diatom taxa : 
Warning messages:
1: In chkinp(taxa, stations) :
  Only diatom or soft-bodied algae present at sites: 404M07357_2016-06-13_1, 801M16916_2016-05-25_1, 909M24937_2016-06-22_1
2: Column `FinalID` joining character vector and factor, coercing into character vector 
3: Column `FinalIDassigned` joining factors with different levels, coercing to character vector 
4: Column `FinalIDassigned` joining character vector and factor, coercing into character vector 
5: Column `Metric` joining character vector and factor, coercing into character vector 
6: Column `Metric` joining character vector and factor, coercing into character vector 
7: Column `Metric` joining character vector and factor, coercing into character vector 

and the results is empty

**Comment by stheroux** [comment]
[demo_algae_tax_diatoms_only.xlsx](https://github.com/SCCWRP/ASCI/files/5302895/demo_algae_tax_diatoms_only.xlsx)
[demo_algae_tax_sba_only.xlsx](https://github.com/SCCWRP/ASCI/files/5302896/demo_algae_tax_sba_only.xlsx)

**Comment by r7butler** [comment]
Pushed up a proposed fix, forgot to referece the issue # in the commit message, but the master branch version should now accept algae data with only SBA or only diatoms

**Comment by stheroux** [comment]
Ran this again today --- looks like the calculator is (incorrectly) returning hybrid ASCI scores when only a single assemblage is calculated, but it is (correctly) returning NA for the missing assemblage ASCI. This will need to be changed so that if only a single assemblage is submitted, it returns NA for the the missing assemblage ASCI and also NA for the H_ASCI.

**Comment by stheroux** [comment]
Getting an error message and the scores are not calculating : 
"Error in startsWith(names(test), "H_") : non-character object(s)"

**Comment by r7butler** [comment]
> Getting an error message when I run the demo data and the scores are not calculating :
> "Error in startsWith(names(test), "H_") : non-character object(s)"

Did you install the latest version? I ran the demo data and got no errors right now

![Screen Shot 2020-10-16 at 10 22 24 AM](https://user-images.githubusercontent.com/40872002/96289221-7dce0a00-0f99-11eb-92fc-0e05fc76da7e.png)

**Comment by stheroux** [comment]
Thanks for the fix!
